### ISSUE TITLE
Solution broken

### ISSUE THREAD

**Issue by davidbtosh** [naeemakram/TCP-IP-Socket-Programming-in-C-Sharp.net-Udemy-Course#1]
Hi Naeem.  I am enjoying your Udemy course.  I bought it years ago and learnt a lot but it was more for curiosity sake.  I now have a major application to write using TCP sockets which must perform at optimally so am revisiting your course and especially the new async / await sections which were not there when I first did the course.
I wanted to have a peek at your code first though and have found that in the UdemyAsyncSocketClient solution there is a reference to the LahoreSocketClient project but the actual project is not in source control so you get missing project errors when load into Visual Studio and the code doesn't compile as the project is missing.

Update.  Sorry I see now.  You need to reference that project which is in the server solution.  Maybe these should be in the same solution?  Or shared somehow.  Broken reference in the solution is confusing.

**Comment by naeemakram** [comment]
Great, yes I updated the course in 2018 to cover async/await. I also added a section about introduction to socket programming. The working code is attached to various videos of the course as well. This repo is here for sake of putting things out there as I mentioned in the course a few times. 
Is this problem now solved or you want me to do something to the solution?
